apiVersion: apps/v1
kind: Deployment
metadata:
  name: $PROJECT_NAME
  labels:
    app: $PROJECT_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $PROJECT_NAME
  template:
    metadata:
      labels:
        app: $PROJECT_NAME
    spec:
      imagePullSecrets:
#        - name: my-registry-key
        - name: aws-registry-key
      containers:
        - name: $PROJECT_NAME
          image: $IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
